name: KianitRings
version: '1.0.0'
depend: [ItemsAdder]
description: Плагин на кольца. Спонсор - kusiva
authors: Kian1t, kusiva

main: com.kianit.kianitRings.KianitRings
api-version: '1.21.11'
load: POSTWORLD

commands:
  rings:
    permission: OP
    usage: /rings reload